version: "3.8"

networks:
  data_platform:

services:
  #############################################################################
  # POSTGRE
  #############################################################################

  postgresql:
    image: postgres:15.2
    hostname: postgresql
    container_name: ${CONTAINER_PREFIX:-my}-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
    - ${POSTGRES_HOST_PORT:-5432}:5432
    networks:
    - data_platform